### ISSUE TITLE
CONTRIBUTING.md: Document that you need to pull from googlesource.com

### ISSUE THREAD

**Issue by joshlf** [google/mundane#12]
Our `CONTRIBUTING.md` documentation on submitting code was copied from BoringSSL's. As such, it assumes that you know to pull from the googlesource.com repo. Since Mundane is also available on GitHub, it's less obvious in our case.

Concretely, we should document that submissions should be pushed to https://fuchsia.googlesource.com/mundane. It's probably easiest to document that by suggesting the following command to clone: `git clone --recursive https://fuchsia.googlesource.com/mundane`.

**Comment by azriel91** [comment]
[`CONTRIBUTING.md`](https://github.com/google/mundane/blob/master/CONTRIBUTING.md) already includes this, so this issue should be able to be closed.

*(could not resist a chance to tidy up this issue :slightly_smiling_face:)*

**Comment by joshlf** [comment]
Good point!

Closed in b98de2a11f8bb4ec6c18b17faa2ea31aa4996c26.
