### ISSUE TITLE
Build docs.rs documentation with all features enabled

### ISSUE THREAD

**Issue by joshlf** [google/mundane#21]
Now that we're using docs.rs to host our documentation, we need to add metadata to the `Cargo.toml` file to instruct docs.rs to use all build features when building the documentation. By default, it just uses the default features, meaning that we get no documentation for things like the `insecure` feature.

For details on how to do this, see the "Metadata for custom builds" section [here](https://docs.rs/about). In particular, we'll want a section like this:

```toml
[package.metadata.docs.rs]
features = [ "bytes", "insecure", "..." ]
```

In total, we'll want the following features documented:
- `bytes`
- `insecure`
- `kdf`
- `rsa-pkcs1v15`

We'll also want to add a comment on the `[features]` line in `Cargo.toml` reminding developers to update the `[package.metadata.docs.rs]` section when they update the `[features]` section.

**Comment by tsing80** [comment]
@joshlf: https://fuchsia-review.googlesource.com/c/mundane/+/325145
