### ISSUE TITLE
Document items behind feature flags

### ISSUE THREAD

**Issue by taralx** [google/mundane#22]
https://docs.rs/crate/mundane/0.4.2/builds

```
[INFO] [stderr]  Documenting mundane v0.4.2 (/opt/rustwide/workdir)
[INFO] [stderr] error: `[RsaPkcs1v15]` cannot be resolved, ignoring it...
[INFO] [stderr]    --> src/public/rsa/mod.rs:363:26
[INFO] [stderr]     |
[INFO] [stderr] 363 | /// feature is enabled, [`RsaPkcs1v15`].
[INFO] [stderr]     |                          ^^^^^^^^^^^^^ cannot be resolved, ignoring
[INFO] [stderr]     |
```

========

Edit by @joshlf : This issue is now about both fixing this issue and also about documenting all items behind feature flags in general; see [this comment](https://github.com/google/mundane/issues/22#issuecomment-563604661) below.

**Comment by joshlf** [comment]
This seems like a good candidate for the new `#[cfg(doc)]` - we can do `#[cfg(any(doc, feature))]` where we used to do `#[cfg(feature)]` in order to make sure that everything is documented and these links always work.

**Comment by subhojit777** [comment]
Hey @joshlf I was looking into it. I couldn't replicate the problem that is mentioned. I have `rustc 1.39.0` and did `cargo build`, but it ran without any errors. Also, tried with nightly - as per the logs here https://docs.rs/crate/mundane/0.4.2/builds/189489, but still no error. Am I missing anything? I ran build from the project root.

**Comment by joshlf** [comment]
It'll be `cargo doc` that should fail. Try that?

**Comment by subhojit777** [comment]
I have created this init PR https://fuchsia-review.googlesource.com/c/mundane/+/348889. I contains the fix of the `cargo doc` error. I will have to update the documentation.

**Comment by subhojit777** [comment]
@joshlf Please ignore the previous PR https://fuchsia-review.googlesource.com/c/mundane/+/348889. Here is a new one containing all the requested changes https://fuchsia-review.googlesource.com/c/mundane/+/349548 Please check this one.
