### ISSUE TITLE
Replace "whitelist" with "allowlist"

### ISSUE THREAD

**Issue by joshlf** [google/mundane#27]
In `boringssl/bindgen.sh`, we use the term "whitelist" to refer to lists of items that should be included by bindgen when generating bindings. For inclusivity reasons, we should use the term "allowlist" instead.

**Comment by azriel91** [comment]
Heya, I had a go at this, with the change at https://fuchsia-review.googlesource.com/c/mundane/+/474677.

`bindgen`'s option still include `--whitelist-*`, so a text search of the repository still shows that.

**Comment by joshlf** [comment]
Thanks @azriel91! Closed in [this CL](https://fuchsia-review.googlesource.com/c/mundane/+/474677).
