### ISSUE TITLE
How can i  sign the message without hashing

### ISSUE THREAD

**Issue by dwj1210** [google/mundane#33]
I noticed this comment, the function **sign()** will both hashing and signing the message.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/24934234/159864170-70b40fc4-ae15-4177-ad04-0de0cdef1dfc.png">

how can i sign the message without hashing ？

Looking forward to your reply ~

**Comment by joshlf** [comment]
We've decided to deprecate Mundane, so I'm closing this.
