### ISSUE TITLE
Test that symbol version names are correct

### ISSUE THREAD

**Issue by joshlf** [google/mundane#8]
Currently, there's no way to automatically test that the version number in `link` and `link_name` attributes in `boringssl/boringssl.rs` match the version number in `Cargo.toml`. This has already led to an issue: we published 0.2.1 with the version numbers in `boringssl/boringssl.rs` still at 0.2.0, forcing us to fix and release 0.2.2, and yank 0.2.1. We should add an automated test so this sort of issue can't slip through in the future.

**Comment by codeworm96** [comment]
I would like to look at this problem.

**Comment by joshlf** [comment]
Nobody else is working on it to my knowledge, so it's all yours!

**Comment by codeworm96** [comment]
I see. I prefer to make it part of `cargo test` because it is convenient and cool.
Is regex matching enough for this check, or we need to do some kind of parsing of the source code?
(With the help of crates like [syn](https://crates.io/crates/syn), it seems not too hard, but may be too heavy for this check...)

**Comment by joshlf** [comment]
I think it should be sufficient to find every instance of a `link_name` attribute and ensure that it matches the regex `#\[link_name = "__RUST_MUNDANE_X_Y_Z_[A-Za-z0-9_]+"\]`. For the `link` attribute, it should be sufficient to ensure that the exact string `#[link(name = "crypto_X_Y_Z")]` appears exactly once in the file.

As for how to do that, I'd advise a test in the `tests` directory that calls out to a shell script. I would expect it to be much easier to write the test itself using a shell script than in pure Rust.

**Comment by codeworm96** [comment]
I have uploaded a change on Gerrit. Would you please have a look?

**Comment by joshlf** [comment]
Awesome, thanks! In the future, if you want to notify me directly from Gerrit, you can click the "Add Reviewer" button to add me as a reviewer or the "Add CC" button to notify me without adding me as a reviewer. I'm taking a look now!

**Comment by joshlf** [comment]
I've accepted and merged the change; thanks so much for your help with this!
